--============================================--
    -- Data Quality Audit And Profiling --
--============================================--

SELECT 
    SUM(CASE WHEN CUSTOMER_ID IS NULL THEN 1 ELSE 0 END) CUSTOMER_ID,
    SUM(CASE WHEN FIRST_NAME IS NULL THEN 1 ELSE 0 END) AS FIRST_NAME,
    SUM(CASE WHEN MIDDLE_NAME IS NULL THEN 1 ELSE 0 END) AS MIDDLE_NAME,
    SUM(CASE WHEN LAST_NAME IS NULL THEN 1 ELSE 0 END) AS LAST_NAME,
    SUM(CASE WHEN EMAIL IS NULL THEN 1 ELSE 0 END) AS EMAIL,
    SUM(CASE WHEN COUNTRY IS NULL THEN 1 ELSE 0 END) AS COUNTRY,
    SUM(CASE WHEN STATE IS NULL THEN 1 ELSE 0 END) AS STATE,
    SUM(CASE WHEN CITY IS NULL THEN 1 ELSE 0 END) AS CITY,
    SUM(CASE WHEN AGE IS NULL THEN 1 ELSE 0 END) AS AGE,
    SUM(CASE WHEN GENDER IS NULL THEN 1 ELSE 0 END) AS GENDER,
    SUM(CASE WHEN MARITAL_STATUS IS NULL THEN 1 ELSE 0 END) AS MARITAL_STATUS,
    SUM(CASE WHEN ANNUAL_INCOME IS NULL THEN 1 ELSE 0 END) AS ANNUAL_INCOME,
    SUM(CASE WHEN SIGNUP_DATE IS NULL THEN 1 ELSE 0 END) AS SIGNUP_DATE
FROM CUSTOMERS_DATASET;