--============================================--
    -- Data Quality Audit And Profiling --
--============================================--

SELECT
    SUM(CASE WHEN ORDER_ID IS NULL THEN 1 ELSE 0 END) ORDER_ID,
    SUM(CASE WHEN TRACKING_NUMBER IS NULL THEN 1 ELSE 0 END) TRACKING_NUMBER,
    SUM(CASE WHEN CARRIER IS NULL THEN 1 ELSE 0 END) CARRIER,
    SUM(CASE WHEN SHIP_DATE IS NULL THEN 1 ELSE 0 END) SHIP_DATE,
    SUM(CASE WHEN DELIVERY_DATE IS NULL THEN 1 ELSE 0 END) DELIVERY_DATE,
    SUM(CASE WHEN DELIVERY_STATUS IS NULL THEN 1 ELSE 0 END) DELIVERY_STATUS
FROM LOGISTICS_DATASET;