--============================================--
    -- Data Quality Audit And Profiling --
--============================================--

SELECT
    SUM(CASE WHEN ORDER_ID IS NULL THEN 1 ELSE 0 END) ORDER_ID,
    SUM(CASE WHEN CUSTOMER_ID IS NULL THEN 1 ELSE 0 END) CUSTOMER_ID,
    SUM(CASE WHEN SELLER_ID IS NULL THEN 1 ELSE 0 END) SELLER_ID,
    SUM(CASE WHEN PRODUCT_ID IS NULL THEN 1 ELSE 0 END) PRODUCT_ID,
    SUM(CASE WHEN QUANTITY IS NULL THEN 1 ELSE 0 END) QUANTITY,
    SUM(CASE WHEN ORDER_DATE IS NULL THEN 1 ELSE 0 END) ORDER_DATE
FROM ORDERS_DATASET;