--============================================--
    -- Data Quality Audit And Profiling --
--============================================--

SELECT
    SUM(CASE WHEN SELLER_ID IS NULL THEN 1 ELSE 0 END) SELLER_ID,
    SUM(CASE WHEN FIRST_NAME IS NULL THEN 1 ELSE 0 END) FIRST_NAME,
    SUM(CASE WHEN MIDDLE_NAME IS NULL THEN 1 ELSE 0 END) MIDDLE_NAME,
    SUM(CASE WHEN LAST_NAME IS NULL THEN 1 ELSE 0 END) LAST_NAME,
    SUM(CASE WHEN SELLER_RATING IS NULL THEN 1 ELSE 0 END) SELLER_RATING,
    SUM(CASE WHEN ONBOARDING_DATE IS NULL THEN 1 ELSE 0 END) ONBOARDING_DATE,
    SUM(CASE WHEN TOTAL_REVENUE IS NULL THEN 1 ELSE 0 END) TOTAL_REVENUE
FROM SELLERS_DATABASE;